In [1]:
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns
import seaborn as sns; sns.set()
import plotly.plotly as py
import csv
import plotly.graph_objs as go

In [2]:
p_scores = pd.read_csv("personality_scores.csv", delimiter=';')

In [3]:
p_scores.head()

,ID,Section 5 of 6 [I am always prepared.],Section 5 of 6 [I am easily disturbed.],Section 5 of 6 [I am exacting (demanding) in my work.],Section 5 of 6 [I am full of ideas.],Section 5 of 6 [I am interested in people.],Section 5 of 6 [I am not interested in abstract ideas.],Section 5 of 6 [I am not interested in other people's problems.],Section 5 of 6 [I am not really interested in others.],Section 5 of 6 [I am quick to understand things.],...,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,IPIP_HIGH_RISK
0,0,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 3)","(5, 3)","(2, 3)","(2, 5)","(5, 5)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 5)","(5, 3)","(2, 5)","(2, 5)","(5, 5)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,"(3, 5)","(4, 3)","(3, 3)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,"(3, 5)","(4, 5)","(3, 3)","(5, 5)","(2, 5)","(5, 3)","(2, 3)","(2, 3)","(5, 3)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,"(3, 3)","(4, 5)","(3, 3)","(5, 3)","(2, 3)","(5, 3)","(2, 3)","(2, 3)","(5, 5)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
p_scores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1555 entries, 0 to 1554
Data columns (total 70 columns):
ID                                                                          1555 non-null int64
Section 5 of 6 [I am always prepared.]                                      1555 non-null object
Section 5 of 6 [I am easily disturbed.]                                     1555 non-null object
Section 5 of 6 [I am exacting (demanding) in my work.]                      1555 non-null object
Section 5 of 6 [I am full of ideas.]                                        1555 non-null object
Section 5 of 6 [I am interested in people.]                                 1555 non-null object
Section 5 of 6 [I am not interested in abstract ideas.]                     1555 non-null object
Section 5 of 6 [I am not interested in other people's problems.]            1555 non-null object
Section 5 of 6 [I am not really interested in others.]                      1555 non-null object
Section 5 of 6 [I am quick to understand things.]                           1555 non-null object
Section 5 of 6 [I am quiet around strangers.]                               1555 non-null object
Section 5 of 6 [I am relaxed most of the time.]                             1555 non-null object
Section 5 of 6 [I am the life of the party.]                                1555 non-null object
Section 5 of 6 [I change my mood a lot.]                                    1555 non-null object
Section 5 of 6 [I do not have a good imagination.]                          1555 non-null object
Section 5 of 6 [I don't like to draw attention to myself.]                  1555 non-null object
Section 5 of 6 [I don't mind being the center of attention.]                1555 non-null object
Section 5 of 6 [I don't talk a lot.]                                        1555 non-null object
Section 5 of 6 [I feel comfortable around people.]                          1555 non-null object
Section 5 of 6 [I feel little concern for others.]                          1555 non-null object
Section 5 of 6 [I feel others' emotions.]                                   1555 non-null object
Section 5 of 6 [I follow a schedule.]                                       1555 non-null object
Section 5 of 6 [I get chores done right away.]                              1555 non-null object
Section 5 of 6 [I get irritated easily.]                                    1555 non-null object
Section 5 of 6 [I get stressed out easily.]                                 1555 non-null object
Section 5 of 6 [I get upset easily.]                                        1555 non-null object
Section 5 of 6 [I have a rich vocabulary.]                                  1555 non-null object
Section 5 of 6 [I have a soft (kind) heart.]                                1555 non-null object
Section 5 of 6 [I have a vivid imagination.]                                1555 non-null object
Section 5 of 6 [I have difficulty understanding abstract ideas.]            1555 non-null object
Section 5 of 6 [I have excellent ideas.]                                    1555 non-null object
Section 5 of 6 [I have frequent mood swings.]                               1555 non-null object
Section 5 of 6 [I have little to say.]                                      1555 non-null object
Section 5 of 6 [I insult people.]                                           1555 non-null object
Section 5 of 6 [I keep in the background.]                                  1555 non-null object
Section 5 of 6 [I leave my belongings lying around.]                        1555 non-null object
Section 5 of 6 [I like order.]                                              1555 non-null object
Section 5 of 6 [I make a mess of things.]                                   1555 non-null object
Section 5 of 6 [I make people feel at ease.]                                1555 non-null object
Section 5 of 6 [I neglect my duties.]                                       1555 non-null object
Section 5 of 6 [I often feel blue (down).]                                  1555 non-null object
Section 5 of 6 [I often forget to put things back in their proper place]    1555 non-null object
Section 5 of 6 [I pay attention to details.]                                1555 non-null object
Section 5 of 6 [I seldom feel blue (down).]                                 1555 non-null object
Section 5 of 6 [I spend time reflecting on things.]                         1555 non-null object
Section 5 of 6 [I start conversations.]                                     1555 non-null object
Section 5 of 6 [I sympathize with others' feelings.]                        1555 non-null object
Section 5 of 6 [I take time out for others.]                                1555 non-null object
Section 5 of 6 [I talk to a lot of different people at parties.]            1555 non-null object
Section 5 of 6 [I use difficult words.]                                     1555 non-null object
Section 5 of 6 [I worry about things.]                                      1555 non-null object
Unnamed: 51                                                                 0 non-null float64
Unnamed: 52                                                                 0 non-null float64
Unnamed: 53                                                                 0 non-null float64
Unnamed: 54                                                                 0 non-null float64
Unnamed: 55                                                                 0 non-null float64
Unnamed: 56                                                                 0 non-null float64
Unnamed: 57                                                                 0 non-null float64
Unnamed: 58                                                                 0 non-null float64
Unnamed: 59                                                                 0 non-null float64
Unnamed: 60                                                                 0 non-null float64
Unnamed: 61                                                                 0 non-null float64
Unnamed: 62                                                                 0 non-null float64
Unnamed: 63                                                                 0 non-null float64
Unnamed: 64                                                                 0 non-null float64
Unnamed: 65                                                                 0 non-null float64
Unnamed: 66                                                                 0 non-null float64
Unnamed: 67                                                                 0 non-null float64
Unnamed: 68                                                                 0 non-null float64
IPIP_HIGH_RISK                                                              0 non-null float64
dtypes: float64(19), int64(1), object(50)
memory usage: 850.5+ KB

In [5]:
p_scores.describe()

,ID,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,IPIP_HIGH_RISK
count,1555.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,777.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,449.034149,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,388.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,777.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,1165.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,1554.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN